/**
 * 模型预设配置。
 *
 * 当前只保留文本润色供应商预设；本地转写使用 SenseVoice，无云端供应商。
 */

export type ModelType = "polisher";

export type ProviderCategory =
  | "official"      // 官方（OpenAI、Anthropic）
  | "cn_official"   // 国产官方（DeepSeek、Kimi、智谱等）
  | "aggregator"    // 聚合服务（OpenRouter、SiliconFlow 等）
  | "third_party"   // 第三方中转
  | "custom";       // 自定义

export interface ModelCatalogEntry {
  model: string;
  displayName: string;
  description?: string;
  contextWindow?: number;
  inputModalities?: ("text" | "audio" | "image")[];
  recommended?: boolean;
}

export interface ProviderPreset {
  /** 供应商名称 */
  name: string;
  /** i18n key */
  nameKey?: string;
  /** 官网链接 */
  websiteUrl: string;
  /** 获取 API Key 的链接 */
  apiKeyUrl?: string;
  /** API Base URL */
  apiBaseUrl: string;
  /** 分类 */
  category: ProviderCategory;
  /** 支持的模型类型 */
  modelTypes: ModelType[];
  /** 推荐模型目录 */
  models: ModelCatalogEntry[];
  /** 默认模型 */
  defaultModel: string;
  /** API 协议格式 */
  apiFormat: "openai" | "anthropic";
  /** 图标名称（用于 UI 展示） */
  icon?: string;
  /** 图标颜色 */
  iconColor?: string;
  /** 是否为合作伙伴 */
  isPartner?: boolean;
  /** 置顶合作伙伴 */
  primePartner?: boolean;
  /** 说明文本 i18n key */
  descriptionKey?: string;
}

// ─── 润色模型预设 ──────────────────────────────────────────────────────────

export const polisherPresets: ProviderPreset[] = [
  {
    name: "DeepSeek",
    websiteUrl: "https://platform.deepseek.com",
    apiKeyUrl: "https://platform.deepseek.com/api_keys",
    apiBaseUrl: "https://api.deepseek.com",
    category: "cn_official",
    modelTypes: ["polisher"],
    apiFormat: "openai",
    defaultModel: "deepseek-v4-flash",
    icon: "deepseek",
    iconColor: "#1E88E5",
    models: [
      {
        model: "deepseek-v4-flash",
        displayName: "DeepSeek V4 Flash",
        description: "轻量快速，适合语音润色",
        contextWindow: 1000000,
        inputModalities: ["text"],
        recommended: true,
      },
      {
        model: "deepseek-v4-pro",
        displayName: "DeepSeek V4 Pro",
        description: "旗舰模型，适合重度改写",
        contextWindow: 1000000,
        inputModalities: ["text"],
      },
    ],
  },
  {
    name: "Kimi",
    websiteUrl: "https://platform.moonshot.cn",
    apiKeyUrl: "https://platform.moonshot.cn/console/api-keys",
    apiBaseUrl: "https://api.moonshot.cn/v1",
    category: "cn_official",
    modelTypes: ["polisher"],
    apiFormat: "openai",
    defaultModel: "kimi-k2.6",
    icon: "kimi",
    iconColor: "#000000",
    isPartner: true,
    models: [
      {
        model: "kimi-k2.6",
        displayName: "Kimi K2.6",
        description: "当前通用主力，速度快，适合润色",
        contextWindow: 131072,
        inputModalities: ["text"],
        recommended: true,
      },
      {
        model: "kimi-k3",
        displayName: "Kimi K3",
        description: "旗舰模型，效果更强、稍慢",
        contextWindow: 262144,
        inputModalities: ["text"],
      },
    ],
  },
  {
    name: "智谱 AI",
    websiteUrl: "https://open.bigmodel.cn",
    apiKeyUrl: "https://open.bigmodel.cn/usercenter/apikeys",
    apiBaseUrl: "https://open.bigmodel.cn/api/paas/v4",
    category: "cn_official",
    modelTypes: ["polisher"],
    apiFormat: "openai",
    defaultModel: "glm-4.7-flash",
    icon: "zhipu",
    iconColor: "#2B5CE6",
    models: [
      {
        model: "glm-4.7-flash",
        displayName: "GLM-4.7 Flash",
        description: "免费，速度快，适合润色",
        contextWindow: 128000,
        inputModalities: ["text"],
        recommended: true,
      },
      {
        model: "glm-4.6",
        displayName: "GLM-4.6",
        description: "付费旗舰，效果更好",
        contextWindow: 200000,
        inputModalities: ["text"],
      },
    ],
  },
  {
    name: "通义千问",
    websiteUrl: "https://dashscope.aliyun.com",
    apiKeyUrl: "https://dashscope.console.aliyun.com/apiKey",
    apiBaseUrl: "https://dashscope.aliyuncs.com/compatible-mode/v1",
    category: "cn_official",
    modelTypes: ["polisher"],
    apiFormat: "openai",
    defaultModel: "qwen-flash",
    icon: "qwen",
    iconColor: "#6C3FE8",
    models: [
      {
        model: "qwen-flash",
        displayName: "Qwen Flash",
        description: "高频轻量任务首选，约 0.2 元/百万输入",
        contextWindow: 131072,
        inputModalities: ["text"],
        recommended: true,
      },
      {
        model: "qwen-plus",
        displayName: "Qwen Plus",
        description: "均衡性价比，适合要求更高的润色",
        contextWindow: 131072,
        inputModalities: ["text"],
      },
      {
        model: "qwen-turbo",
        displayName: "Qwen Turbo",
        description: "高并发轻量，延迟低",
        contextWindow: 131072,
        inputModalities: ["text"],
      },
    ],
  },
  {
    name: "火山方舟（豆包）",
    websiteUrl: "https://www.volcengine.com/product/doubao",
    apiKeyUrl: "https://console.volcengine.com/ark",
    apiBaseUrl: "https://ark.cn-beijing.volces.com/api/v3",
    category: "cn_official",
    modelTypes: ["polisher"],
    apiFormat: "openai",
    defaultModel: "doubao-seed-1.6-flash-250828",
    iconColor: "#0052FF",
    models: [
      {
        model: "doubao-seed-1.6-flash-250828",
        displayName: "Doubao Seed 1.6 Flash",
        description: "极速版，首字延迟低，适合润色",
        contextWindow: 262144,
        inputModalities: ["text"],
        recommended: true,
      },
      {
        model: "doubao-seed-1.6-flash-250615",
        displayName: "Doubao Seed 1.6 Flash (0615)",
        description: "上一版权重，行为更稳定",
        contextWindow: 262144,
        inputModalities: ["text"],
      },
      {
        model: "doubao-seed-2.0-lite",
        displayName: "Doubao Seed 2.0 Lite",
        description: "新一代轻量版",
        contextWindow: 262144,
        inputModalities: ["text"],
      },
    ],
  },
  {
    name: "百度千帆",
    websiteUrl: "https://cloud.baidu.com/product/qianfan_home",
    apiKeyUrl: "https://console.bce.baidu.com/qianfan/ais/console/applicationConsole/application",
    apiBaseUrl: "https://qianfan.baidubce.com/v2",
    category: "cn_official",
    modelTypes: ["polisher"],
    apiFormat: "openai",
    defaultModel: "ernie-4.5-turbo-128k",
    iconColor: "#2932E1",
    models: [
      {
        model: "ernie-4.5-turbo-128k",
        displayName: "ERNIE 4.5 Turbo 128K",
        description: "主力模型，速度快、价格低",
        contextWindow: 128000,
        inputModalities: ["text"],
        recommended: true,
      },
      {
        model: "ernie-4.5-turbo-32k",
        displayName: "ERNIE 4.5 Turbo 32K",
        description: "短上下文版本，更便宜",
        contextWindow: 32000,
        inputModalities: ["text"],
      },
      {
        model: "ernie-5.0",
        displayName: "ERNIE 5.0",
        description: "旗舰模型，效果更好",
        contextWindow: 128000,
        inputModalities: ["text"],
      },
    ],
  },
  {
    name: "MiniMax",
    websiteUrl: "https://www.minimaxi.com",
    apiKeyUrl: "https://platform.minimaxi.com/user-center/basic-information/interface-key",
    apiBaseUrl: "https://api.minimaxi.com/v1",
    category: "cn_official",
    modelTypes: ["polisher"],
    apiFormat: "openai",
    defaultModel: "MiniMax-M3",
    iconColor: "#E34D4C",
    models: [
      {
        model: "MiniMax-M3",
        displayName: "MiniMax M3",
        description: "旗舰模型（默认自适应思考，应用会自动关闭）",
        contextWindow: 1000000,
        inputModalities: ["text"],
        recommended: true,
      },
      {
        model: "abab6.5s-chat",
        displayName: "abab6.5s",
        description: "上一代轻量模型，无思考、便宜",
        contextWindow: 131072,
        inputModalities: ["text"],
      },
    ],
  },
  {
    name: "OpenAI",
    websiteUrl: "https://platform.openai.com",
    apiKeyUrl: "https://platform.openai.com/api-keys",
    apiBaseUrl: "https://api.openai.com/v1",
    category: "official",
    modelTypes: ["polisher"],
    apiFormat: "openai",
    defaultModel: "gpt-4o-mini",
    icon: "openai",
    iconColor: "#10A37F",
    models: [
      {
        model: "gpt-4o-mini",
        displayName: "GPT-4o Mini",
        description: "快速、经济的多模态模型",
        contextWindow: 128000,
        inputModalities: ["text", "image"],
        recommended: true,
      },
      {
        model: "gpt-4o",
        displayName: "GPT-4o",
        description: "旗舰多模态模型",
        contextWindow: 128000,
        inputModalities: ["text", "image"],
      },
    ],
  },
  {
    name: "Anthropic",
    websiteUrl: "https://console.anthropic.com",
    apiKeyUrl: "https://console.anthropic.com/settings/keys",
    apiBaseUrl: "https://api.anthropic.com",
    category: "official",
    modelTypes: ["polisher"],
    apiFormat: "anthropic",
    defaultModel: "claude-sonnet-4-20250514",
    icon: "anthropic",
    iconColor: "#D4915D",
    models: [
      {
        model: "claude-sonnet-4-20250514",
        displayName: "Claude Sonnet 4",
        description: "平衡性能与速度",
        contextWindow: 200000,
        inputModalities: ["text", "image"],
        recommended: true,
      },
      {
        model: "claude-haiku-3.5",
        displayName: "Claude Haiku 3.5",
        description: "快速响应，成本低",
        contextWindow: 200000,
        inputModalities: ["text", "image"],
      },
    ],
  },
  {
    name: "Google Gemini",
    websiteUrl: "https://deepmind.google/models/gemini/",
    apiKeyUrl: "https://aistudio.google.com/apikey",
    apiBaseUrl: "https://generativelanguage.googleapis.com/v1beta/openai",
    category: "official",
    modelTypes: ["polisher"],
    apiFormat: "openai",
    defaultModel: "gemini-2.5-flash-lite",
    iconColor: "#4285F4",
    models: [
      {
        model: "gemini-2.5-flash-lite",
        displayName: "Gemini 2.5 Flash-Lite",
        description: "最快最便宜，默认不思考",
        contextWindow: 1000000,
        inputModalities: ["text", "image"],
        recommended: true,
      },
      {
        model: "gemini-3.1-flash-lite",
        displayName: "Gemini 3.1 Flash-Lite",
        description: "新一代轻量模型",
        contextWindow: 1000000,
        inputModalities: ["text", "image"],
      },
    ],
  },
  {
    name: "SiliconFlow",
    websiteUrl: "https://siliconflow.cn",
    apiKeyUrl: "https://cloud.siliconflow.cn/account/ak",
    apiBaseUrl: "https://api.siliconflow.cn/v1",
    category: "aggregator",
    modelTypes: ["polisher"],
    apiFormat: "openai",
    defaultModel: "Qwen/Qwen3-8B",
    icon: "siliconflow",
    iconColor: "#4F46E5",
    models: [
      {
        model: "Qwen/Qwen3-8B",
        displayName: "Qwen3 8B",
        description: "免费模型，速度快，适合轻度润色",
        contextWindow: 32768,
        inputModalities: ["text"],
        recommended: true,
      },
      {
        model: "deepseek-ai/DeepSeek-V3",
        displayName: "DeepSeek V3",
        description: "高质量通用模型",
        contextWindow: 65536,
        inputModalities: ["text"],
      },
    ],
  },
  {
    name: "OpenRouter",
    websiteUrl: "https://openrouter.ai",
    apiKeyUrl: "https://openrouter.ai/settings/keys",
    apiBaseUrl: "https://openrouter.ai/api/v1",
    category: "aggregator",
    modelTypes: ["polisher"],
    apiFormat: "openai",
    defaultModel: "deepseek/deepseek-v4-flash",
    iconColor: "#6566F1",
    models: [
      {
        model: "deepseek/deepseek-v4-flash",
        displayName: "DeepSeek V4 Flash",
        description: "一个密钥用各家模型，此为高性价比默认",
        contextWindow: 1000000,
        inputModalities: ["text"],
        recommended: true,
      },
      {
        model: "google/gemini-2.5-flash-lite",
        displayName: "Gemini 2.5 Flash-Lite",
        description: "快速便宜，默认不思考",
        contextWindow: 1000000,
        inputModalities: ["text", "image"],
      },
    ],
  },
  {
    name: "Ollama（本地）",
    websiteUrl: "https://ollama.com",
    apiBaseUrl: "http://localhost:11434",
    category: "custom",
    modelTypes: ["polisher"],
    apiFormat: "openai",
    defaultModel: "qwen2.5:7b",
    iconColor: "#0F6E6B",
    models: [
      {
        model: "qwen2.5:7b",
        displayName: "Qwen2.5 7B",
        description: "本地运行，无需思考；密钥任意填写即可（如 ollama）",
        contextWindow: 32768,
        inputModalities: ["text"],
        recommended: true,
      },
      {
        model: "llama3.1:8b",
        displayName: "Llama 3.1 8B",
        description: "本地运行，通用能力强",
        contextWindow: 131072,
        inputModalities: ["text"],
      },
      {
        model: "qwen2.5:3b",
        displayName: "Qwen2.5 3B",
        description: "本地运行，低配机器可用",
        contextWindow: 32768,
        inputModalities: ["text"],
      },
    ],
  },
  // ----- official -----
  // ----- cn_official -----
  {
    name: "Kimi (Anthropic)",
    websiteUrl: "https://platform.kimi.com",
    apiBaseUrl: "https://api.moonshot.cn/anthropic",
    category: "cn_official",
    modelTypes: ["polisher"],
    apiFormat: "anthropic",
    defaultModel: "kimi-k2.7-code",
    iconColor: "#6366F1",
    models: [
      { model: "kimi-k2.7-code", displayName: "kimi-k2.7-code", recommended: true },
    ],
  },
  {
    name: "Kimi For Coding",
    websiteUrl: "https://www.kimi.com/code",
    apiBaseUrl: "https://api.kimi.com/coding/",
    category: "cn_official",
    modelTypes: ["polisher"],
    apiFormat: "anthropic",
    defaultModel: "kimi-for-coding",
    iconColor: "#6366F1",
    models: [
      { model: "kimi-for-coding", displayName: "kimi-for-coding", recommended: true },
    ],
  },
  {
    name: "火山 Agent Plan",
    websiteUrl: "https://www.volcengine.com/activity/agentplan",
    apiKeyUrl: "https://www.volcengine.com/activity/agentplan",
    apiBaseUrl: "https://ark.cn-beijing.volces.com/api/plan",
    category: "cn_official",
    modelTypes: ["polisher"],
    apiFormat: "anthropic",
    defaultModel: "ark-code-latest",
    iconColor: "#3370FF",
    models: [
      { model: "ark-code-latest", displayName: "ark-code-latest", recommended: true },
    ],
  },
  {
    name: "火山 Coding Plan",
    websiteUrl: "https://www.volcengine.com/activity/codingplan",
    apiKeyUrl: "https://www.volcengine.com/activity/codingplan",
    apiBaseUrl: "https://ark.cn-beijing.volces.com/api/coding",
    category: "cn_official",
    modelTypes: ["polisher"],
    apiFormat: "anthropic",
    defaultModel: "ark-code-latest",
    iconColor: "#3370FF",
    models: [
      { model: "ark-code-latest", displayName: "ark-code-latest", recommended: true },
    ],
  },
  {
    name: "BytePlus",
    websiteUrl: "https://www.byteplus.com/en/product/modelark",
    apiKeyUrl: "https://www.byteplus.com/en/product/modelark",
    apiBaseUrl: "https://ark.ap-southeast.bytepluses.com/api/coding",
    category: "cn_official",
    modelTypes: ["polisher"],
    apiFormat: "anthropic",
    defaultModel: "ark-code-latest",
    iconColor: "#3370FF",
    models: [
      { model: "ark-code-latest", displayName: "ark-code-latest", recommended: true },
    ],
  },
  {
    name: "DouBaoSeed",
    websiteUrl: "https://console.volcengine.com/ark/region:ark+cn-beijing/apiKey",
    apiKeyUrl: "https://console.volcengine.com/ark/region:ark+cn-beijing/apiKey",
    apiBaseUrl: "https://ark.cn-beijing.volces.com/api/compatible",
    category: "cn_official",
    modelTypes: ["polisher"],
    apiFormat: "anthropic",
    defaultModel: "doubao-seed-2-1-pro-260628",
    iconColor: "#3370FF",
    models: [
      { model: "doubao-seed-2-1-pro-260628", displayName: "doubao-seed-2-1-pro-260628", recommended: true },
    ],
  },
  {
    name: "DeepSeek (Anthropic)",
    websiteUrl: "https://platform.deepseek.com",
    apiBaseUrl: "https://api.deepseek.com/anthropic",
    category: "cn_official",
    modelTypes: ["polisher"],
    apiFormat: "anthropic",
    defaultModel: "deepseek-v4-pro",
    iconColor: "#1E88E5",
    models: [
      { model: "deepseek-v4-pro", displayName: "deepseek-v4-pro", recommended: true },
    ],
  },
  {
    name: "Zhipu GLM",
    websiteUrl: "https://open.bigmodel.cn",
    apiKeyUrl: "https://www.bigmodel.cn/claude-code",
    apiBaseUrl: "https://open.bigmodel.cn/api/anthropic",
    category: "cn_official",
    modelTypes: ["polisher"],
    apiFormat: "anthropic",
    defaultModel: "glm-5.1",
    iconColor: "#0F62FE",
    models: [
      { model: "glm-5.1", displayName: "glm-5.1", recommended: true },
    ],
  },
  {
    name: "Zhipu GLM en",
    websiteUrl: "https://z.ai",
    apiKeyUrl: "https://z.ai/subscribe",
    apiBaseUrl: "https://api.z.ai/api/anthropic",
    category: "cn_official",
    modelTypes: ["polisher"],
    apiFormat: "anthropic",
    defaultModel: "glm-5.1",
    iconColor: "#0F62FE",
    models: [
      { model: "glm-5.1", displayName: "glm-5.1", recommended: true },
    ],
  },
  {
    name: "Baidu Qianfan Coding Plan",
    websiteUrl: "https://cloud.baidu.com/product/qianfan_modelbuilder",
    apiKeyUrl: "https://console.bce.baidu.com/qianfan/ais/console/applicationConsole/application",
    apiBaseUrl: "https://qianfan.baidubce.com/anthropic/coding",
    category: "cn_official",
    modelTypes: ["polisher"],
    apiFormat: "anthropic",
    defaultModel: "qianfan-code-latest",
    iconColor: "#2932E1",
    models: [
      { model: "qianfan-code-latest", displayName: "qianfan-code-latest", recommended: true },
    ],
  },
  {
    name: "Baidu Qianfan Token Plan",
    websiteUrl: "https://cloud.baidu.com/product/codingplan.html",
    apiKeyUrl: "https://console.bce.baidu.com/qianfan/resource/token-plan",
    apiBaseUrl: "https://qianfan.baidubce.com/anthropic/tokenplan/personal",
    category: "cn_official",
    modelTypes: ["polisher"],
    apiFormat: "anthropic",
    defaultModel: "deepseek-v4-pro",
    iconColor: "#2932E1",
    models: [
      { model: "deepseek-v4-pro", displayName: "deepseek-v4-pro", recommended: true },
    ],
  },
  {
    name: "Bailian",
    websiteUrl: "https://bailian.console.aliyun.com",
    apiBaseUrl: "https://dashscope.aliyuncs.com/apps/anthropic",
    category: "cn_official",
    modelTypes: ["polisher"],
    apiFormat: "anthropic",
    defaultModel: "",
    iconColor: "#624AFF",
    models: [],
  },
  {
    name: "Bailian For Coding",
    websiteUrl: "https://bailian.console.aliyun.com",
    apiBaseUrl: "https://coding.dashscope.aliyuncs.com/apps/anthropic",
    category: "cn_official",
    modelTypes: ["polisher"],
    apiFormat: "anthropic",
    defaultModel: "",
    iconColor: "#624AFF",
    models: [],
  },
  {
    name: "StepFun",
    websiteUrl: "https://platform.stepfun.com/step-plan",
    apiKeyUrl: "https://platform.stepfun.com/interface-key",
    apiBaseUrl: "https://api.stepfun.com/step_plan",
    category: "cn_official",
    modelTypes: ["polisher"],
    apiFormat: "anthropic",
    defaultModel: "step-3.5-flash-2603",
    iconColor: "#16D6D2",
    models: [
      { model: "step-3.5-flash-2603", displayName: "step-3.5-flash-2603", recommended: true },
    ],
  },
  {
    name: "StepFun en",
    websiteUrl: "https://platform.stepfun.ai/step-plan",
    apiKeyUrl: "https://platform.stepfun.ai/interface-key",
    apiBaseUrl: "https://api.stepfun.ai/step_plan",
    category: "cn_official",
    modelTypes: ["polisher"],
    apiFormat: "anthropic",
    defaultModel: "step-3.5-flash-2603",
    iconColor: "#16D6D2",
    models: [
      { model: "step-3.5-flash-2603", displayName: "step-3.5-flash-2603", recommended: true },
    ],
  },
  {
    name: "KAT-Coder",
    websiteUrl: "https://console.streamlake.ai",
    apiKeyUrl: "https://console.streamlake.ai/console/api-key",
    apiBaseUrl: "https://vanchin.streamlake.ai/api/gateway/v1/endpoints/${ENDPOINT_ID}/claude-code-proxy",
    category: "cn_official",
    modelTypes: ["polisher"],
    apiFormat: "anthropic",
    defaultModel: "KAT-Coder-Pro V1",
    models: [
      { model: "KAT-Coder-Pro V1", displayName: "KAT-Coder-Pro V1", recommended: true },
    ],
  },
  {
    name: "Longcat",
    websiteUrl: "https://longcat.chat/platform",
    apiKeyUrl: "https://longcat.chat/platform/api_keys",
    apiBaseUrl: "https://api.longcat.chat/anthropic",
    category: "cn_official",
    modelTypes: ["polisher"],
    apiFormat: "anthropic",
    defaultModel: "LongCat-2.0",
    iconColor: "#29E154",
    models: [
      { model: "LongCat-2.0", displayName: "LongCat-2.0", recommended: true },
    ],
  },
  {
    name: "MiniMax (Anthropic)",
    websiteUrl: "https://platform.minimaxi.com",
    apiKeyUrl: "https://platform.minimaxi.com/subscribe/coding-plan",
    apiBaseUrl: "https://api.minimaxi.com/anthropic",
    category: "cn_official",
    modelTypes: ["polisher"],
    apiFormat: "anthropic",
    defaultModel: "MiniMax-M2.7",
    iconColor: "#FF6B6B",
    models: [
      { model: "MiniMax-M2.7", displayName: "MiniMax-M2.7", recommended: true },
    ],
  },
  {
    name: "MiniMax en",
    websiteUrl: "https://platform.minimax.io",
    apiKeyUrl: "https://platform.minimax.io/subscribe/coding-plan",
    apiBaseUrl: "https://api.minimax.io/anthropic",
    category: "cn_official",
    modelTypes: ["polisher"],
    apiFormat: "anthropic",
    defaultModel: "MiniMax-M2.7",
    iconColor: "#FF6B6B",
    models: [
      { model: "MiniMax-M2.7", displayName: "MiniMax-M2.7", recommended: true },
    ],
  },
  {
    name: "BaiLing",
    websiteUrl: "https://alipaytbox.yuque.com/sxs0ba/ling/get_started",
    apiBaseUrl: "https://api.tbox.cn/api/anthropic",
    category: "cn_official",
    modelTypes: ["polisher"],
    apiFormat: "anthropic",
    defaultModel: "Ling-2.5-1T",
    models: [
      { model: "Ling-2.5-1T", displayName: "Ling-2.5-1T", recommended: true },
    ],
  },
  {
    name: "Xiaomi MiMo",
    websiteUrl: "https://platform.xiaomimimo.com",
    apiKeyUrl: "https://platform.xiaomimimo.com",
    apiBaseUrl: "https://api.xiaomimimo.com/anthropic",
    category: "cn_official",
    modelTypes: ["polisher"],
    apiFormat: "anthropic",
    defaultModel: "mimo-v2.5-pro",
    iconColor: "#000000",
    models: [
      { model: "mimo-v2.5-pro", displayName: "mimo-v2.5-pro", recommended: true },
    ],
  },
  {
    name: "Xiaomi MiMo Token Plan (China)",
    websiteUrl: "https://platform.xiaomimimo.com",
    apiKeyUrl: "https://platform.xiaomimimo.com",
    apiBaseUrl: "https://token-plan-cn.xiaomimimo.com/anthropic",
    category: "cn_official",
    modelTypes: ["polisher"],
    apiFormat: "anthropic",
    defaultModel: "mimo-v2.5-pro",
    iconColor: "#000000",
    models: [
      { model: "mimo-v2.5-pro", displayName: "mimo-v2.5-pro", recommended: true },
    ],
  },
  {
    name: "Kimi For Coding (OpenAI)",
    websiteUrl: "https://www.kimi.com/code",
    apiKeyUrl: "https://www.kimi.com/code",
    apiBaseUrl: "https://api.kimi.com/coding/v1",
    category: "cn_official",
    modelTypes: ["polisher"],
    apiFormat: "openai",
    defaultModel: "kimi-for-coding",
    iconColor: "#6366F1",
    models: [
      { model: "kimi-for-coding", displayName: "Kimi For Coding", contextWindow: 262144 },
      { model: "kimi-for-coding-highspeed", displayName: "Kimi For Coding HighSpeed", contextWindow: 262144 },
      { model: "k3", displayName: "Kimi K3", contextWindow: 1048576 },
      { model: "k3-256k", displayName: "Kimi K3 256K", contextWindow: 262144 },
    ],
  },
  {
    name: "Zhipu GLM (OpenAI)",
    websiteUrl: "https://open.bigmodel.cn",
    apiKeyUrl: "https://www.bigmodel.cn/claude-code",
    apiBaseUrl: "https://open.bigmodel.cn/api/coding/paas/v4",
    category: "cn_official",
    modelTypes: ["polisher"],
    apiFormat: "openai",
    defaultModel: "glm-5.2",
    iconColor: "#0F62FE",
    models: [
      { model: "glm-5.2", displayName: "GLM-5.2", contextWindow: 200000 },
    ],
  },
  {
    name: "Zhipu GLM en (OpenAI)",
    websiteUrl: "https://z.ai",
    apiKeyUrl: "https://z.ai/subscribe",
    apiBaseUrl: "https://api.z.ai/api/coding/paas/v4",
    category: "cn_official",
    modelTypes: ["polisher"],
    apiFormat: "openai",
    defaultModel: "glm-5.2",
    iconColor: "#0F62FE",
    models: [
      { model: "glm-5.2", displayName: "GLM-5.2", contextWindow: 200000 },
    ],
  },
  {
    name: "Baidu Qianfan Coding Plan (OpenAI)",
    websiteUrl: "https://cloud.baidu.com/product/qianfan_modelbuilder",
    apiKeyUrl: "https://console.bce.baidu.com/qianfan/ais/console/applicationConsole/application",
    apiBaseUrl: "https://qianfan.baidubce.com/v2/coding",
    category: "cn_official",
    modelTypes: ["polisher"],
    apiFormat: "openai",
    defaultModel: "qianfan-code-latest",
    iconColor: "#2932E1",
    models: [
      { model: "qianfan-code-latest", displayName: "Qianfan Code Latest", contextWindow: 131072 },
    ],
  },
  {
    name: "Baidu Qianfan Token Plan (OpenAI)",
    websiteUrl: "https://cloud.baidu.com/product/codingplan.html",
    apiKeyUrl: "https://console.bce.baidu.com/qianfan/resource/token-plan",
    apiBaseUrl: "https://qianfan.baidubce.com/v2/tokenplan/personal",
    category: "cn_official",
    modelTypes: ["polisher"],
    apiFormat: "openai",
    defaultModel: "deepseek-v4-pro",
    iconColor: "#2932E1",
    models: [
      { model: "deepseek-v4-pro", displayName: "DeepSeek V4 Pro", contextWindow: 1048576 },
      { model: "deepseek-v4-flash", displayName: "DeepSeek V4 Flash", contextWindow: 1048576 },
      { model: "deepseek-v4-flash-0731", displayName: "DeepSeek V4 Flash 0731", contextWindow: 1048576 },
      { model: "glm-5.2", displayName: "GLM-5.2", contextWindow: 1048576 },
      { model: "glm-5.1", displayName: "GLM-5.1", contextWindow: 198000 },
      { model: "kimi-k2.6", displayName: "Kimi K2.6", contextWindow: 262144 },
    ],
  },
  {
    name: "StepFun (OpenAI)",
    websiteUrl: "https://platform.stepfun.com/step-plan",
    apiKeyUrl: "https://platform.stepfun.com/interface-key",
    apiBaseUrl: "https://api.stepfun.com/step_plan/v1",
    category: "cn_official",
    modelTypes: ["polisher"],
    apiFormat: "openai",
    defaultModel: "step-3.7-flash",
    iconColor: "#16D6D2",
    models: [
      { model: "step-3.7-flash", displayName: "Step 3.7 Flash", contextWindow: 262144 },
      { model: "step-3.5-flash-2603", displayName: "Step 3.5 Flash 2603", contextWindow: 262144 },
      { model: "step-3.5-flash", displayName: "Step 3.5 Flash", contextWindow: 262144 },
    ],
  },
  {
    name: "StepFun en (OpenAI)",
    websiteUrl: "https://platform.stepfun.ai/step-plan",
    apiKeyUrl: "https://platform.stepfun.ai/interface-key",
    apiBaseUrl: "https://api.stepfun.ai/step_plan/v1",
    category: "cn_official",
    modelTypes: ["polisher"],
    apiFormat: "openai",
    defaultModel: "step-3.7-flash",
    iconColor: "#16D6D2",
    models: [
      { model: "step-3.7-flash", displayName: "Step 3.7 Flash", contextWindow: 262144 },
      { model: "step-3.5-flash-2603", displayName: "Step 3.5 Flash 2603", contextWindow: 262144 },
      { model: "step-3.5-flash", displayName: "Step 3.5 Flash", contextWindow: 262144 },
    ],
  },
  {
    name: "BaiLing (OpenAI)",
    websiteUrl: "https://alipaytbox.yuque.com/sxs0ba/ling/get_started",
    apiKeyUrl: "https://ling.tbox.cn/open",
    apiBaseUrl: "https://api.tbox.cn/api/llm/v1",
    category: "cn_official",
    modelTypes: ["polisher"],
    apiFormat: "openai",
    defaultModel: "Ling-2.6-1T",
    models: [
      { model: "Ling-2.6-1T", displayName: "Ling-2.6-1T", contextWindow: 262144 },
    ],
  },
  // ----- aggregator -----
  {
    name: "ZetaAPI",
    websiteUrl: "https://zetaapi.ai",
    apiKeyUrl: "https://zetaapi.ai/go/u117",
    apiBaseUrl: "https://api.zetaapi.ai",
    category: "aggregator",
    modelTypes: ["polisher"],
    apiFormat: "anthropic",
    defaultModel: "",
    models: [],
  },
  {
    name: "FennoAI",
    websiteUrl: "https://api.fenno.ai",
    apiKeyUrl: "https://api.fenno.ai/register",
    apiBaseUrl: "https://api.fenno.ai",
    category: "aggregator",
    modelTypes: ["polisher"],
    apiFormat: "anthropic",
    defaultModel: "",
    models: [],
  },
  {
    name: "RunAPI",
    websiteUrl: "https://runapi.host",
    apiKeyUrl: "https://runapi.host/register",
    apiBaseUrl: "https://runapi.host",
    category: "aggregator",
    modelTypes: ["polisher"],
    apiFormat: "anthropic",
    defaultModel: "",
    models: [],
  },
  {
    name: "Shengsuanyun",
    websiteUrl: "https://www.shengsuanyun.com",
    apiKeyUrl: "https://www.shengsuanyun.com",
    apiBaseUrl: "https://router.shengsuanyun.com/api",
    category: "aggregator",
    modelTypes: ["polisher"],
    apiFormat: "anthropic",
    defaultModel: "anthropic/claude-sonnet-5",
    models: [
      { model: "anthropic/claude-sonnet-5", displayName: "anthropic/claude-sonnet-5", recommended: true },
    ],
  },
  {
    name: "Qiniu",
    websiteUrl: "https://s.qiniu.com/nMvAvy",
    apiKeyUrl: "https://s.qiniu.com/nMvAvy",
    apiBaseUrl: "https://api.qnaigc.com",
    category: "aggregator",
    modelTypes: ["polisher"],
    apiFormat: "anthropic",
    defaultModel: "",
    models: [],
  },
  {
    name: "SubRouter",
    websiteUrl: "https://subrouter.ai",
    apiKeyUrl: "https://subrouter.ai/register",
    apiBaseUrl: "https://subrouter.ai",
    category: "aggregator",
    modelTypes: ["polisher"],
    apiFormat: "anthropic",
    defaultModel: "",
    models: [],
  },
  {
    name: "ClaudeAPI",
    websiteUrl: "https://www.apito.ai",
    apiKeyUrl: "https://console.apito.ai/agent/register/pQBql2buaqiX3dDS",
    apiBaseUrl: "https://gw.apito.ai",
    category: "aggregator",
    modelTypes: ["polisher"],
    apiFormat: "anthropic",
    defaultModel: "",
    models: [],
  },
  {
    name: "Code0",
    websiteUrl: "https://code0.ai",
    apiKeyUrl: "https://code0.ai/agent/register/B2XHxGjGmRvqgznY",
    apiBaseUrl: "https://code0.ai",
    category: "aggregator",
    modelTypes: ["polisher"],
    apiFormat: "anthropic",
    defaultModel: "",
    models: [],
  },
  {
    name: "TeamoRouter",
    websiteUrl: "https://teamorouter.com",
    apiKeyUrl: "https://teamorouter.com",
    apiBaseUrl: "https://api.teamorouter.com",
    category: "aggregator",
    modelTypes: ["polisher"],
    apiFormat: "anthropic",
    defaultModel: "",
    models: [],
  },
  {
    name: "PPIO",
    websiteUrl: "https://ppio.com",
    apiKeyUrl: "https://ppio.com/activity/ccswitch",
    apiBaseUrl: "https://api.ppio.com/anthropic",
    category: "aggregator",
    modelTypes: ["polisher"],
    apiFormat: "anthropic",
    defaultModel: "deepseek/deepseek-v4-flash-0731",
    iconColor: "#2874FF",
    models: [
      { model: "deepseek/deepseek-v4-flash-0731", displayName: "deepseek/deepseek-v4-flash-0731", recommended: true },
    ],
  },
  {
    name: "SiliconFlow (Anthropic)",
    websiteUrl: "https://siliconflow.cn",
    apiKeyUrl: "https://cloud.siliconflow.cn/i/YflgU2Ve",
    apiBaseUrl: "https://api.siliconflow.cn",
    category: "aggregator",
    modelTypes: ["polisher"],
    apiFormat: "anthropic",
    defaultModel: "Pro/MiniMaxAI/MiniMax-M2.5",
    iconColor: "#6E29F6",
    models: [
      { model: "Pro/MiniMaxAI/MiniMax-M2.5", displayName: "Pro/MiniMaxAI/MiniMax-M2.5", recommended: true },
    ],
  },
  {
    name: "SiliconFlow en",
    websiteUrl: "https://siliconflow.com",
    apiKeyUrl: "https://cloud.siliconflow.cn/i/YflgU2Ve",
    apiBaseUrl: "https://api.siliconflow.com",
    category: "aggregator",
    modelTypes: ["polisher"],
    apiFormat: "anthropic",
    defaultModel: "MiniMaxAI/MiniMax-M3",
    iconColor: "#000000",
    models: [
      { model: "MiniMaxAI/MiniMax-M3", displayName: "MiniMaxAI/MiniMax-M3", recommended: true },
    ],
  },
  {
    name: "A6API",
    websiteUrl: "https://www.a6api.com",
    apiKeyUrl: "https://a6api.com/register",
    apiBaseUrl: "https://api.a6api.com",
    category: "aggregator",
    modelTypes: ["polisher"],
    apiFormat: "anthropic",
    defaultModel: "",
    models: [],
  },
  {
    name: "AtlasCloud",
    websiteUrl: "https://www.atlascloud.ai/console/coding-plan",
    apiKeyUrl: "https://www.atlascloud.ai/console/coding-plan",
    apiBaseUrl: "https://api.atlascloud.ai",
    category: "aggregator",
    modelTypes: ["polisher"],
    apiFormat: "anthropic",
    defaultModel: "zai-org/glm-5.1",
    models: [
      { model: "zai-org/glm-5.1", displayName: "zai-org/glm-5.1", recommended: true },
    ],
  },
  {
    name: "Compshare",
    websiteUrl: "https://www.compshare.cn",
    apiKeyUrl: "https://www.compshare.cn/coding-plan",
    apiBaseUrl: "https://api.modelverse.cn",
    category: "aggregator",
    modelTypes: ["polisher"],
    apiFormat: "anthropic",
    defaultModel: "",
    iconColor: "#000000",
    models: [],
  },
  {
    name: "Compshare Coding Plan",
    websiteUrl: "https://www.compshare.cn",
    apiKeyUrl: "https://www.compshare.cn/coding-plan",
    apiBaseUrl: "https://cp.compshare.cn",
    category: "aggregator",
    modelTypes: ["polisher"],
    apiFormat: "anthropic",
    defaultModel: "",
    iconColor: "#000000",
    models: [],
  },
  {
    name: "CCSub",
    websiteUrl: "https://www.ccsub.net",
    apiKeyUrl: "https://www.ccsub.net/register",
    apiBaseUrl: "https://www.ccsub.net",
    category: "aggregator",
    modelTypes: ["polisher"],
    apiFormat: "anthropic",
    defaultModel: "",
    models: [],
  },
  {
    name: "DMXAPI",
    websiteUrl: "https://www.dmxapi.cn",
    apiKeyUrl: "https://www.dmxapi.cn",
    apiBaseUrl: "https://www.dmxapi.cn",
    category: "aggregator",
    modelTypes: ["polisher"],
    apiFormat: "anthropic",
    defaultModel: "",
    models: [],
  },
  {
    name: "XycAi",
    websiteUrl: "https://xycai.us",
    apiKeyUrl: "https://xycai.us/register",
    apiBaseUrl: "https://apicdn.xycai.us",
    category: "aggregator",
    modelTypes: ["polisher"],
    apiFormat: "anthropic",
    defaultModel: "",
    models: [],
  },
  {
    name: "Amux",
    websiteUrl: "https://amux.ai",
    apiKeyUrl: "https://amux.ai",
    apiBaseUrl: "https://api.amux.ai",
    category: "aggregator",
    modelTypes: ["polisher"],
    apiFormat: "anthropic",
    defaultModel: "",
    models: [],
  },
  {
    name: "ModelScope",
    websiteUrl: "https://modelscope.cn",
    apiBaseUrl: "https://api-inference.modelscope.cn",
    category: "aggregator",
    modelTypes: ["polisher"],
    apiFormat: "anthropic",
    defaultModel: "ZhipuAI/GLM-5.2",
    iconColor: "#624AFF",
    models: [
      { model: "ZhipuAI/GLM-5.2", displayName: "ZhipuAI/GLM-5.2", recommended: true },
    ],
  },
  {
    name: "AiHubMix",
    websiteUrl: "https://aihubmix.com",
    apiKeyUrl: "https://aihubmix.com",
    apiBaseUrl: "https://aihubmix.com",
    category: "aggregator",
    modelTypes: ["polisher"],
    apiFormat: "anthropic",
    defaultModel: "",
    iconColor: "#006FFB",
    models: [],
  },
  {
    name: "CherryIN",
    websiteUrl: "https://open.cherryin.ai",
    apiKeyUrl: "https://open.cherryin.ai/console/token",
    apiBaseUrl: "https://open.cherryin.net",
    category: "aggregator",
    modelTypes: ["polisher"],
    apiFormat: "anthropic",
    defaultModel: "anthropic/claude-sonnet-5",
    models: [
      { model: "anthropic/claude-sonnet-5", displayName: "anthropic/claude-sonnet-5", recommended: true },
    ],
  },
  {
    name: "OpenRouter (Anthropic)",
    websiteUrl: "https://openrouter.ai",
    apiKeyUrl: "https://openrouter.ai/keys",
    apiBaseUrl: "https://openrouter.ai/api",
    category: "aggregator",
    modelTypes: ["polisher"],
    apiFormat: "anthropic",
    defaultModel: "anthropic/claude-sonnet-5",
    iconColor: "#6566F1",
    models: [
      { model: "anthropic/claude-sonnet-5", displayName: "anthropic/claude-sonnet-5", recommended: true },
    ],
  },
  {
    name: "TheRouter",
    websiteUrl: "https://therouter.ai",
    apiKeyUrl: "https://dashboard.therouter.ai",
    apiBaseUrl: "https://api.therouter.ai",
    category: "aggregator",
    modelTypes: ["polisher"],
    apiFormat: "anthropic",
    defaultModel: "anthropic/claude-sonnet-5",
    models: [
      { model: "anthropic/claude-sonnet-5", displayName: "anthropic/claude-sonnet-5", recommended: true },
    ],
  },
  {
    name: "Novita AI",
    websiteUrl: "https://novita.ai",
    apiKeyUrl: "https://novita.ai",
    apiBaseUrl: "https://api.novita.ai/anthropic",
    category: "aggregator",
    modelTypes: ["polisher"],
    apiFormat: "anthropic",
    defaultModel: "zai-org/glm-5.1",
    iconColor: "#000000",
    models: [
      { model: "zai-org/glm-5.1", displayName: "zai-org/glm-5.1", recommended: true },
    ],
  },
  {
    name: "Nvidia",
    websiteUrl: "https://build.nvidia.com",
    apiKeyUrl: "https://build.nvidia.com/settings/api-keys",
    apiBaseUrl: "https://integrate.api.nvidia.com",
    category: "aggregator",
    modelTypes: ["polisher"],
    apiFormat: "openai",
    defaultModel: "moonshotai/kimi-k2.5",
    iconColor: "#000000",
    models: [
      { model: "moonshotai/kimi-k2.5", displayName: "moonshotai/kimi-k2.5", recommended: true },
    ],
  },
  {
    name: "PIPELLM",
    websiteUrl: "https://code.pipellm.ai",
    apiKeyUrl: "https://code.pipellm.ai/login",
    apiBaseUrl: "https://cc-api.pipellm.ai",
    category: "aggregator",
    modelTypes: ["polisher"],
    apiFormat: "anthropic",
    defaultModel: "claude-opus-5",
    models: [
      { model: "claude-opus-5", displayName: "claude-opus-5", recommended: true },
    ],
  },
  {
    name: "JieKou AI",
    websiteUrl: "https://jiekou.ai",
    apiKeyUrl: "https://jiekou.ai/settings/key-management",
    apiBaseUrl: "https://api.jiekou.ai/anthropic",
    category: "aggregator",
    modelTypes: ["polisher"],
    apiFormat: "anthropic",
    defaultModel: "claude-fable-5",
    iconColor: "#000000",
    models: [
      { model: "claude-fable-5", displayName: "claude-fable-5", recommended: true },
    ],
  },
  {
    name: "PPIO (OpenAI)",
    websiteUrl: "https://ppio.com",
    apiKeyUrl: "https://ppio.com/activity/ccswitch",
    apiBaseUrl: "https://api.ppio.com/openai/v1",
    category: "aggregator",
    modelTypes: ["polisher"],
    apiFormat: "openai",
    defaultModel: "deepseek/deepseek-v4-flash-0731",
    iconColor: "#2874FF",
    models: [
      { model: "deepseek/deepseek-v4-flash-0731", displayName: "Deepseek V4 Flash 0731", contextWindow: 1048576, inputModalities: ["text"] },
    ],
  },
  {
    name: "SiliconFlow en (OpenAI)",
    websiteUrl: "https://siliconflow.com",
    apiKeyUrl: "https://cloud.siliconflow.cn/i/YflgU2Ve",
    apiBaseUrl: "https://api.siliconflow.com/v1",
    category: "aggregator",
    modelTypes: ["polisher"],
    apiFormat: "openai",
    defaultModel: "MiniMaxAI/MiniMax-M3",
    iconColor: "#000000",
    models: [
      { model: "MiniMaxAI/MiniMax-M3", displayName: "MiniMax M3", contextWindow: 1048576 },
    ],
  },
  {
    name: "AtlasCloud (OpenAI)",
    websiteUrl: "https://www.atlascloud.ai/console/coding-plan",
    apiKeyUrl: "https://www.atlascloud.ai/console/coding-plan",
    apiBaseUrl: "https://api.atlascloud.ai/v1",
    category: "aggregator",
    modelTypes: ["polisher"],
    apiFormat: "openai",
    defaultModel: "zai-org/glm-5.1",
    models: [
      { model: "zai-org/glm-5.1", displayName: "GLM 5.1", contextWindow: 200000 },
    ],
  },
  {
    name: "ModelScope (OpenAI)",
    websiteUrl: "https://modelscope.cn",
    apiKeyUrl: "https://modelscope.cn/my/myaccesstoken",
    apiBaseUrl: "https://api-inference.modelscope.cn/v1",
    category: "aggregator",
    modelTypes: ["polisher"],
    apiFormat: "openai",
    defaultModel: "ZhipuAI/GLM-5.2",
    iconColor: "#624AFF",
    models: [
      { model: "ZhipuAI/GLM-5.2", displayName: "ZhipuAI / GLM-5.2", contextWindow: 200000 },
    ],
  },
  {
    name: "Novita AI (OpenAI)",
    websiteUrl: "https://novita.ai",
    apiKeyUrl: "https://novita.ai",
    apiBaseUrl: "https://api.novita.ai/openai/v1",
    category: "aggregator",
    modelTypes: ["polisher"],
    apiFormat: "openai",
    defaultModel: "zai-org/glm-5.1",
    iconColor: "#000000",
    models: [
      { model: "zai-org/glm-5.1", displayName: "GLM-5.1", contextWindow: 202800 },
    ],
  },
  {
    name: "Nvidia (OpenAI)",
    websiteUrl: "https://build.nvidia.com",
    apiKeyUrl: "https://build.nvidia.com/settings/api-keys",
    apiBaseUrl: "https://integrate.api.nvidia.com/v1",
    category: "aggregator",
    modelTypes: ["polisher"],
    apiFormat: "openai",
    defaultModel: "moonshotai/kimi-k2.5",
    iconColor: "#000000",
    models: [
      { model: "moonshotai/kimi-k2.5", displayName: "Kimi K2.5", contextWindow: 262144 },
    ],
  },
  {
    name: "JieKou AI (OpenAI)",
    websiteUrl: "https://jiekou.ai",
    apiKeyUrl: "https://jiekou.ai/settings/key-management",
    apiBaseUrl: "https://api.jiekou.ai/openai/v1",
    category: "aggregator",
    modelTypes: ["polisher"],
    apiFormat: "openai",
    defaultModel: "claude-fable-5",
    iconColor: "#000000",
    models: [
      { model: "claude-fable-5", displayName: "Claude Fable 5", contextWindow: 1000000, inputModalities: ["text","image"] },
    ],
  },
  // ----- third_party -----
  {
    name: "PackyCode",
    websiteUrl: "https://www.packyapi.ai",
    apiKeyUrl: "https://www.packyapi.ai/register",
    apiBaseUrl: "https://www.packyapi.ai",
    category: "third_party",
    modelTypes: ["polisher"],
    apiFormat: "anthropic",
    defaultModel: "",
    models: [],
  },
  {
    name: "APINebula",
    websiteUrl: "https://apinebula.ai",
    apiKeyUrl: "https://apinebula.ai/VjM74M",
    apiBaseUrl: "https://apinebula.ai",
    category: "third_party",
    modelTypes: ["polisher"],
    apiFormat: "anthropic",
    defaultModel: "",
    models: [],
  },
  {
    name: "AICodeMirror",
    websiteUrl: "https://www.aicodemirror.ai",
    apiKeyUrl: "https://www.aicodemirror.ai/register",
    apiBaseUrl: "https://api.aicodemirror.ai/api/claudecode",
    category: "third_party",
    modelTypes: ["polisher"],
    apiFormat: "anthropic",
    defaultModel: "",
    iconColor: "#000000",
    models: [],
  },
  {
    name: "PatewayAI",
    websiteUrl: "https://pateway.ai",
    apiKeyUrl: "https://pateway.ai",
    apiBaseUrl: "https://api.pateway.ai",
    category: "third_party",
    modelTypes: ["polisher"],
    apiFormat: "anthropic",
    defaultModel: "",
    models: [],
  },
  {
    name: "AIGoCode",
    websiteUrl: "https://aigocode.app",
    apiKeyUrl: "https://aigocode.app/invite/CC-SWITCH",
    apiBaseUrl: "https://api.aigocode.app",
    category: "third_party",
    modelTypes: ["polisher"],
    apiFormat: "anthropic",
    defaultModel: "",
    iconColor: "#5B7FFF",
    models: [],
  },
  {
    name: "AICoding",
    websiteUrl: "https://aicoding.inc",
    apiKeyUrl: "https://aicoding.inc/i/CCSWITCH",
    apiBaseUrl: "https://api.aicoding.inc",
    category: "third_party",
    modelTypes: ["polisher"],
    apiFormat: "anthropic",
    defaultModel: "",
    iconColor: "#000000",
    models: [],
  },
  {
    name: "APIKEY.FUN",
    websiteUrl: "https://apikey.fun",
    apiKeyUrl: "https://apikey.fun/register",
    apiBaseUrl: "https://api.apikey.fun",
    category: "third_party",
    modelTypes: ["polisher"],
    apiFormat: "anthropic",
    defaultModel: "",
    models: [],
  },
  {
    name: "ClaudeCN",
    websiteUrl: "https://claudecn.top",
    apiKeyUrl: "https://claudecn.ai/register",
    apiBaseUrl: "https://claudecn.top",
    category: "third_party",
    modelTypes: ["polisher"],
    apiFormat: "anthropic",
    defaultModel: "",
    models: [],
  },
  {
    name: "SSSAiCode",
    websiteUrl: "https://sssaicodeapi.com",
    apiKeyUrl: "https://sssaicodeapi.com/register",
    apiBaseUrl: "https://node-hk.sssaicodeapi.com/api",
    category: "third_party",
    modelTypes: ["polisher"],
    apiFormat: "anthropic",
    defaultModel: "",
    iconColor: "#000000",
    models: [],
  },
  {
    name: "Micu",
    websiteUrl: "https://www.micuapi.ai",
    apiKeyUrl: "https://www.micuapi.ai/register",
    apiBaseUrl: "https://www.micuapi.ai",
    category: "third_party",
    modelTypes: ["polisher"],
    apiFormat: "anthropic",
    defaultModel: "",
    iconColor: "#000000",
    models: [],
  },
  {
    name: "RightCode",
    websiteUrl: "https://www.rightapi.ai",
    apiKeyUrl: "https://www.rightapi.ai/register",
    apiBaseUrl: "https://www.rightapi.ai/claude",
    category: "third_party",
    modelTypes: ["polisher"],
    apiFormat: "anthropic",
    defaultModel: "",
    iconColor: "#E96B2C",
    models: [],
  },
  {
    name: "ETok.ai",
    websiteUrl: "https://etok.ai",
    apiKeyUrl: "https://etok.ai",
    apiBaseUrl: "https://api.etok.ai",
    category: "third_party",
    modelTypes: ["polisher"],
    apiFormat: "anthropic",
    defaultModel: "",
    iconColor: "#000000",
    models: [],
  },
  {
    name: "Cubence",
    websiteUrl: "https://cubence.com",
    apiKeyUrl: "https://cubence.com/signup",
    apiBaseUrl: "https://api.cubence.com",
    category: "third_party",
    modelTypes: ["polisher"],
    apiFormat: "anthropic",
    defaultModel: "",
    iconColor: "#000000",
    models: [],
  },
  {
    name: "CrazyRouter",
    websiteUrl: "https://www.crazyrouter.com",
    apiKeyUrl: "https://www.crazyrouter.com/register",
    apiBaseUrl: "https://cn.crazyrouter.com",
    category: "third_party",
    modelTypes: ["polisher"],
    apiFormat: "anthropic",
    defaultModel: "",
    iconColor: "#000000",
    models: [],
  },
  {
    name: "SudoCode.chat",
    websiteUrl: "https://sudocode.chat",
    apiKeyUrl: "https://sudocode.chat/sign-up",
    apiBaseUrl: "https://api.sudocode.chat",
    category: "third_party",
    modelTypes: ["polisher"],
    apiFormat: "anthropic",
    defaultModel: "",
    models: [],
  },
  {
    name: "SudoCode.us",
    websiteUrl: "https://sudocode.us",
    apiKeyUrl: "https://sudocode.us",
    apiBaseUrl: "https://sudocode.us",
    category: "third_party",
    modelTypes: ["polisher"],
    apiFormat: "anthropic",
    defaultModel: "",
    models: [],
  },
  {
    name: "OpenCode Go",
    websiteUrl: "https://opencode.ai/go",
    apiKeyUrl: "https://opencode.ai/go",
    apiBaseUrl: "https://opencode.ai/zen/go",
    category: "third_party",
    modelTypes: ["polisher"],
    apiFormat: "anthropic",
    defaultModel: "deepseek-v4-flash",
    iconColor: "#211E1E",
    models: [
      { model: "deepseek-v4-flash", displayName: "deepseek-v4-flash", recommended: true },
    ],
  },
  {
    name: "RelaxyCode",
    websiteUrl: "https://www.relaxycode.com",
    apiKeyUrl: "https://www.relaxycode.com/register",
    apiBaseUrl: "https://www.relaxycode.com",
    category: "third_party",
    modelTypes: ["polisher"],
    apiFormat: "anthropic",
    defaultModel: "",
    models: [],
  },
  {
    name: "E-FlowCode",
    websiteUrl: "https://e-flowcode.cc",
    apiKeyUrl: "https://e-flowcode.cc",
    apiBaseUrl: "https://e-flowcode.cc",
    category: "third_party",
    modelTypes: ["polisher"],
    apiFormat: "anthropic",
    defaultModel: "",
    iconColor: "#000000",
    models: [],
  },
  {
    name: "OpenCode Go (OpenAI)",
    websiteUrl: "https://opencode.ai/go",
    apiKeyUrl: "https://opencode.ai/go",
    apiBaseUrl: "https://opencode.ai/zen/go/v1",
    category: "third_party",
    modelTypes: ["polisher"],
    apiFormat: "openai",
    defaultModel: "glm-5.2",
    iconColor: "#211E1E",
    models: [
      { model: "glm-5.2", displayName: "GLM 5.2", contextWindow: 204800 },
      { model: "glm-5.1", displayName: "GLM 5.1", contextWindow: 204800 },
      { model: "kimi-k2.7-code", displayName: "Kimi K2.7 Code", contextWindow: 262144 },
      { model: "deepseek-v4-pro", displayName: "DeepSeek V4 Pro", contextWindow: 1048576 },
      { model: "deepseek-v4-flash", displayName: "DeepSeek V4 Flash", contextWindow: 1048576 },
      { model: "mimo-v2.5-pro", displayName: "MiMo V2.5 Pro", contextWindow: 1048576 },
    ],
  },
];

export const categoryOrder: ProviderCategory[] = [
  "official",
  "cn_official",
  "aggregator",
  "third_party",
  "custom",
];

export const categoryLabels: Record<ProviderCategory, string> = {
  official: "官方",
  cn_official: "国产",
  aggregator: "聚合服务",
  third_party: "第三方中转",
  custom: "本地/自定义",
};

export const categoryLabelsEn: Record<ProviderCategory, string> = {
  official: "Official",
  cn_official: "Chinese",
  aggregator: "Aggregator",
  third_party: "Third-party",
  custom: "Local/Custom",
};
